### ISSUE TITLE
[插件名称] 反馈内容

### ISSUE THREAD

**Issue by ink5897** [AtmoOmen/DalamudPlugins#11]
> [!WARNING]
>
> 此处不接受任何形式的功能建议，仅用于问题反馈

**插件名称**: [GatherBuddyReborn](https://github.com/AtmoOmen/GatherBuddyReborn)

**插件版本**: 6.58.2.18

**反馈内容**: 采集雷之水晶的时候，雷之碎晶和雷之水晶在一个采集点，会选择采集雷之碎晶

- [x] 我已确认：相关插件已为最新版本
- [x] 我已确认：可以在**仅**开启相关插件/相关功能的情况下稳定复现相关内容

**Comment by AtmoOmen** [comment]
我不参与该插件开发，请向上游反馈
