### ISSUE TITLE
请求给V(ery) island追加中文的前缀移除

### ISSUE THREAD

**Issue by status102** [AtmoOmen/DalamudPlugins#4]
https://github.com/awgil/ffxiv_visland/blob/master/ffxiv_visland/Workshop/WorkshopOCImport.cs#L450-L464

上游仓库中对于物品名简写的前缀移除只有英文部分，请问方便加上中文的前缀移除吗，十分感谢
`海岛` 和 `开拓工房`

效果如下
![image](https://github.com/AtmoOmen/DalamudPlugins/assets/102887808/bdbb2c52-b7d0-4320-8267-e9fe5c2791f6)

**Comment by AtmoOmen** [comment]
修改为, 未测试:
```cs
public static string OfficialNameToBotName(string name)
{
    if (name.StartsWith("海岛"))
        return name.Remove(0, 2);
    if (name.StartsWith("开拓工房"))
        return name.Remove(0, 4);
    return name;
}
```

**Comment by status102** [comment]
十分感谢
