### ISSUE TITLE
[Daily Routine] 活动日历页面无法加载

### ISSUE THREAD

**Issue by distance011** [AtmoOmen/DalamudPlugins#8]
> [!WARNING]
>
> 此处不接受任何形式的功能建议，仅用于问题反馈

**插件名称**: DR

**插件版本**: 0.5.5.4 CN server

**反馈内容**: 
活动日历页稳定无法加载，更新日志无法查询，且cnsl无任何err/wrn log
使用代理/clash/直连均稳定复现

复现频率：必现

- [x] 已确认：相关插件已为最新版本
- [x] 已确认：可以在**仅**开启相关插件/相关功能的情况下稳定复现相关内容

**Comment by AtmoOmen** [comment]
国服版本目前已停止一切联网服务，7.0前不再进行任何维护
