### ISSUE TITLE
[GatherBuddyReborn] 采集碎晶不对

### ISSUE THREAD

**Issue by akazhuo** [AtmoOmen/DalamudPlugins#9]
> [!WARNING]
>
> 此处不接受任何形式的功能建议，仅用于问题反馈

**插件名称**: 
GatherBuddyReborn
**插件版本**: 
最新
**反馈内容**: 
比如采集“风之碎晶”挖了“冰之碎晶”或是指定风之水晶挖了风之碎晶。

- [x] 我已确认：相关插件已为最新版本
- [x] 我已确认：可以在**仅**开启相关插件/相关功能的情况下稳定复现相关内容

**Comment by AtmoOmen** [comment]
麻烦反馈至上游，我不负责该插件的开发
